# Configurations
title:            Alex Veden Quantitative Trader / Data-Scientist / Python Developer
longtitle:        Alex Veden Blog
author:           Alex Veden
email:            i@alexveden.com
description: >
  My work on my way of quantitative trader, data scientist. My project portfolio as Python and C developer. 

version:          1.0
gitbook_version:  3.2.3

url:              'https://alexveden.github.io'
baseurl:          ''
rss:              RSS

# bootstrap: use the remote theme for the site itself
# remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/img/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:categories/:year-:month-:day-:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts
  - Makefile
  - tmux_run.sh

collections:
  collection_about:
    position: 1
    title: About me
    output: true
    permalink: /about/:path/
  # collection_book_c:
  #   position: 2
  #   title: My book 1
  #   output: true
  #   permalink: /modern-c-book/:path/
  posts:
    position: 3
    # title: Recent posts
    output: true


page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji


# Custom settings
github_username:    alexveden
